/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

/**
 *
 * @author Dell
 */
public class choose_manage extends javax.swing.JFrame {

    /**
     * Creates new form choose_manage
     */
    public choose_manage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bEmployee = new javax.swing.JButton();
        bPayroll = new javax.swing.JButton();
        bReports = new javax.swing.JButton();
        bButton0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bEmployee.setBackground(new java.awt.Color(204, 204, 204));
        bEmployee.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        bEmployee.setText("Employee Management ");
        bEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmployeeActionPerformed(evt);
            }
        });

        bPayroll.setBackground(new java.awt.Color(204, 204, 204));
        bPayroll.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        bPayroll.setText("Payroll Management");
        bPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPayrollActionPerformed(evt);
            }
        });

        bReports.setBackground(new java.awt.Color(204, 204, 204));
        bReports.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        bReports.setText("Reports Management");
        bReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReportsActionPerformed(evt);
            }
        });

        bButton0.setBackground(java.awt.SystemColor.controlHighlight);
        bButton0.setText("BACK");
        bButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bButton0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bReports, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(bButton0)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(bButton0)
                .addGap(36, 36, 36)
                .addComponent(bEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(bPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(bReports, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmployeeActionPerformed
        Employee_select empSelect;
        Employee_select Employee_select = empSelect = new Employee_select();
        empSelect.show(); //displays choose_manage here
        dispose();
        
        
    }//GEN-LAST:event_bEmployeeActionPerformed

    private void bPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPayrollActionPerformed
        payroll_management payrollman;
        payroll_management payroll_management = payrollman = new payroll_management();
        payrollman.show(); //displays choose_manage here
        dispose();
    }//GEN-LAST:event_bPayrollActionPerformed

    private void bReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReportsActionPerformed
        reports_management reportsman;
        reports_management reports_management = reportsman = new reports_management();
        reportsman.show();
        dispose();
    }//GEN-LAST:event_bReportsActionPerformed

    private void bButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButton0ActionPerformed
        LogIn_Credentials bButton0 = bButton0 = new LogIn_Credentials();
         bButton0.show(); //displays choose_manage here
         dispose(); 
    }//GEN-LAST:event_bButton0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choose_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choose_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choose_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choose_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choose_manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bButton0;
    private javax.swing.JButton bEmployee;
    private javax.swing.JButton bPayroll;
    private javax.swing.JButton bReports;
    // End of variables declaration//GEN-END:variables
}
