/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.school.motorphpayroll;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rashni alicand
 */
public class AdminPayroll extends javax.swing.JFrame {

    /**
     * Creates new form admin_payroll
     */
    public AdminPayroll() {
        initComponents();
    }

    
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgmain = new javax.swing.JPanel();
        top_panel = new javax.swing.JPanel();
        emp_mgt = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rep_mgt = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pay_mgt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        exit_onadmin = new javax.swing.JLabel();
        logout_onadmin = new javax.swing.JLabel();
        page_panel = new javax.swing.JPanel();
        emp_mgt_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        emp_no_pay = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        l_name_no_pay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        f_name_no_pay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        address_no_pay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        phone_no_pay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sss_no_pay = new javax.swing.JTextField();
        phil_no_pay = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tin_no_pay = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        hdmf_no_pay = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        status_no_pay = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        position_no_pay = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        sup_no_pay = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        basic_no_pay = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        rice_no_pay = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        phone_allow_no_pay = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cloth_no_pay = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        gross_no_pay = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        hourly_no_pay = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        bday_no_pay = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        pay_mgt_panel = new javax.swing.JPanel();
        emp_numberlbl = new javax.swing.JLabel();
        emp_no_payroll = new javax.swing.JTextField();
        employee_details_label = new javax.swing.JLabel();
        emp_namelbl1 = new javax.swing.JLabel();
        emp_name_payroll = new javax.swing.JTextField();
        search_payroll = new javax.swing.JButton();
        emp_positionlbl = new javax.swing.JLabel();
        emp_position_payroll = new javax.swing.JTextField();
        start_datelbl = new javax.swing.JLabel();
        start_date_payroll = new javax.swing.JTextField();
        end_datelbl3 = new javax.swing.JLabel();
        end_date_payroll = new javax.swing.JTextField();
        payslip_details_label = new javax.swing.JLabel();
        benefits_lable = new javax.swing.JLabel();
        end_datelbl4 = new javax.swing.JLabel();
        rice_payroll = new javax.swing.JTextField();
        phone_allow_label = new javax.swing.JLabel();
        phone_payroll = new javax.swing.JTextField();
        clothing_lbl = new javax.swing.JLabel();
        cloth_payroll = new javax.swing.JTextField();
        benefits_lable1 = new javax.swing.JLabel();
        monthly_ratelbl = new javax.swing.JLabel();
        monthly_rate_payroll = new javax.swing.JTextField();
        semi_ratelbl = new javax.swing.JLabel();
        semi_rate_payroll = new javax.swing.JTextField();
        daily_ratelbl = new javax.swing.JLabel();
        daily_rate_payroll = new javax.swing.JTextField();
        total_ben_label = new javax.swing.JLabel();
        total_ben_payroll = new javax.swing.JTextField();
        days_workedlbl = new javax.swing.JLabel();
        days_worked_payroll = new javax.swing.JTextField();
        overtime_lbl = new javax.swing.JLabel();
        overtime_payroll = new javax.swing.JTextField();
        gross_label = new javax.swing.JLabel();
        total_deduct_label = new javax.swing.JLabel();
        total_deduct_payroll = new javax.swing.JTextField();
        tax_payroll = new javax.swing.JTextField();
        tax_label = new javax.swing.JLabel();
        phil_label = new javax.swing.JLabel();
        phil_payroll = new javax.swing.JTextField();
        sss_payroll = new javax.swing.JTextField();
        sss_label = new javax.swing.JLabel();
        benefits_lable2 = new javax.swing.JLabel();
        calcu_Netpay = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        benefits_lable3 = new javax.swing.JLabel();
        end_datelbl6 = new javax.swing.JLabel();
        gross_inc_payroll_sum = new javax.swing.JTextField();
        phone_allow_label2 = new javax.swing.JLabel();
        total_ben_payroll_sum = new javax.swing.JTextField();
        clothing_lbl4 = new javax.swing.JLabel();
        total_deduct_payroll_sum = new javax.swing.JTextField();
        clothing_lbl5 = new javax.swing.JLabel();
        net_pay = new javax.swing.JTextField();
        benefits_lable4 = new javax.swing.JLabel();
        pag_ibig_label = new javax.swing.JLabel();
        pag_ibig_payroll = new javax.swing.JTextField();
        benefits_lable5 = new javax.swing.JLabel();
        pag_ibig_payroll_comp = new javax.swing.JTextField();
        pag_ibig_payroll_comp_label = new javax.swing.JLabel();
        phil_label1 = new javax.swing.JLabel();
        phil_payroll1 = new javax.swing.JTextField();
        gross_inc_payroll = new javax.swing.JTextField();
        twh_payroll = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tdw_payroll = new javax.swing.JTextField();
        twd_payroll = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        rep_mgt_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgmain.setBackground(new java.awt.Color(255, 255, 255));
        bgmain.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgmainMouseDragged(evt);
            }
        });
        bgmain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgmainMousePressed(evt);
            }
        });
        bgmain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top_panel.setBackground(new java.awt.Color(51, 51, 255));
        top_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emp_mgt.setBackground(new java.awt.Color(255, 255, 255));
        emp_mgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emp_mgtMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setLabelFor(emp_mgt);
        jLabel1.setText("Eployee Management");

        javax.swing.GroupLayout emp_mgtLayout = new javax.swing.GroupLayout(emp_mgt);
        emp_mgt.setLayout(emp_mgtLayout);
        emp_mgtLayout.setHorizontalGroup(
            emp_mgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emp_mgtLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        emp_mgtLayout.setVerticalGroup(
            emp_mgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emp_mgtLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        top_panel.add(emp_mgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 230, 50));

        rep_mgt.setBackground(new java.awt.Color(204, 204, 204));
        rep_mgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rep_mgtMouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setLabelFor(rep_mgt);
        jLabel3.setText("Reports Management");

        javax.swing.GroupLayout rep_mgtLayout = new javax.swing.GroupLayout(rep_mgt);
        rep_mgt.setLayout(rep_mgtLayout);
        rep_mgtLayout.setHorizontalGroup(
            rep_mgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rep_mgtLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        rep_mgtLayout.setVerticalGroup(
            rep_mgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rep_mgtLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );

        top_panel.add(rep_mgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 210, 50));

        pay_mgt.setBackground(new java.awt.Color(204, 204, 204));
        pay_mgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pay_mgtMouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setLabelFor(pay_mgt);
        jLabel2.setText("Payroll Management");

        javax.swing.GroupLayout pay_mgtLayout = new javax.swing.GroupLayout(pay_mgt);
        pay_mgt.setLayout(pay_mgtLayout);
        pay_mgtLayout.setHorizontalGroup(
            pay_mgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pay_mgtLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(49, 49, 49))
        );
        pay_mgtLayout.setVerticalGroup(
            pay_mgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pay_mgtLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18))
        );

        top_panel.add(pay_mgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 210, 50));

        exit_onadmin.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        exit_onadmin.setForeground(new java.awt.Color(204, 0, 0));
        exit_onadmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_onadmin.setText("X");
        exit_onadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_onadminMouseClicked(evt);
            }
        });
        top_panel.add(exit_onadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, -1, -1));

        logout_onadmin.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        logout_onadmin.setForeground(new java.awt.Color(255, 255, 255));
        logout_onadmin.setText("Log out");
        logout_onadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_onadminMouseClicked(evt);
            }
        });
        top_panel.add(logout_onadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 60, -1));

        bgmain.add(top_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 80));

        page_panel.setBackground(new java.awt.Color(0, 102, 102));
        page_panel.setForeground(new java.awt.Color(0, 102, 102));
        page_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emp_mgt_panel.setBackground(new java.awt.Color(255, 255, 255));
        emp_mgt_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        emp_mgt_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 32, 403, 709));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Employee Number");
        emp_mgt_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 86, 120, 25));

        emp_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emp_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_no_pay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emp_mgt_panel.add(emp_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 86, 152, 25));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Last Name");
        emp_mgt_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 118, 120, 25));

        l_name_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l_name_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(l_name_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 117, 302, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("First Name");
        emp_mgt_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 120, 25));

        f_name_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        f_name_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(f_name_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 149, 302, 25));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Birthday");
        emp_mgt_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 182, 120, 25));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Address");
        emp_mgt_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 214, 120, 25));

        address_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        address_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(address_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 213, 513, 25));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Phone Number");
        emp_mgt_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 246, 120, 25));

        phone_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phone_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(phone_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 245, 170, 25));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("SSS Number");
        emp_mgt_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 481, 120, 25));

        sss_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sss_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(sss_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 480, 177, 25));

        phil_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phil_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(phil_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 512, 177, 25));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Philhealth Number");
        emp_mgt_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 513, 120, 25));

        tin_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tin_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(tin_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 544, 177, 25));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("Tax Identification Number");
        emp_mgt_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 545, -1, 25));

        hdmf_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hdmf_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(hdmf_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 576, 177, 25));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText("Pag-ibig Number");
        emp_mgt_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 577, 120, 25));

        status_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        status_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(status_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 321, 154, 25));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("Status");
        emp_mgt_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 322, 120, 25));

        position_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        position_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(position_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 353, 226, 25));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 255));
        jLabel15.setText("Position");
        emp_mgt_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 354, 120, 25));

        sup_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sup_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(sup_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 385, 226, 25));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 255));
        jLabel16.setText("Immediate Supervisor");
        emp_mgt_panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 386, -1, 25));

        basic_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        basic_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(basic_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 480, 177, 25));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 255));
        jLabel17.setText("Basic Salary");
        emp_mgt_panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 477, 120, 25));

        rice_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rice_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(rice_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 511, 177, 25));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 255));
        jLabel18.setText("Rice Subsidy");
        emp_mgt_panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 508, 120, 25));

        phone_allow_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phone_allow_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(phone_allow_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 542, 177, 25));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 255));
        jLabel19.setText("Phone Allowance");
        emp_mgt_panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 539, 120, 25));

        cloth_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cloth_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(cloth_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 573, 177, 25));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setText("Clothing Allowance");
        emp_mgt_panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 159, 25));

        gross_no_pay.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        gross_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(gross_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 604, 177, 25));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 255));
        jLabel21.setText("Gross Semi-monthly Rate");
        emp_mgt_panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 601, -1, 25));

        hourly_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hourly_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(hourly_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 635, 177, 25));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 255));
        jLabel22.setText("Hourly Rate");
        emp_mgt_panel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 632, 120, 25));

        btn_update.setBackground(new java.awt.Color(255, 153, 51));
        btn_update.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_update.setForeground(java.awt.Color.white);
        btn_update.setText("Update");
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMouseClicked(evt);
            }
        });
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        emp_mgt_panel.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 708, 154, 33));

        btn_save.setBackground(new java.awt.Color(51, 204, 0));
        btn_save.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        emp_mgt_panel.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 708, 147, 33));

        btn_clear.setBackground(new java.awt.Color(255, 0, 0));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_clear.setForeground(java.awt.Color.white);
        btn_clear.setText("Clear");
        btn_clear.setToolTipText("");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        emp_mgt_panel.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1157, 708, 137, 33));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Government Statutory Details");
        emp_mgt_panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 448, 329, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Employment Details");
        emp_mgt_panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 289, 309, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 255));
        jLabel25.setText("Benefits");
        emp_mgt_panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 448, 310, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Employee Details");
        emp_mgt_panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 48, 309, -1));

        bday_no_pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bday_no_pay.setForeground(new java.awt.Color(51, 51, 255));
        emp_mgt_panel.add(bday_no_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 181, 170, 25));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 255));
        jLabel27.setText("DATE FORMAT: MM/DD/YYYY)");
        jLabel27.setEnabled(false);
        emp_mgt_panel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 189, 141, -1));

        btn_search.setBackground(new java.awt.Color(153, 204, 255));
        btn_search.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_search.setText("Search");
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });
        emp_mgt_panel.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 708, 152, 33));

        page_panel.add(emp_mgt_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 770));

        pay_mgt_panel.setBackground(new java.awt.Color(255, 255, 255));
        pay_mgt_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emp_numberlbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        emp_numberlbl.setForeground(new java.awt.Color(0, 0, 255));
        emp_numberlbl.setText("Employee Number");
        pay_mgt_panel.add(emp_numberlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 69, 121, 25));

        emp_no_payroll.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        emp_no_payroll.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pay_mgt_panel.add(emp_no_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 68, 157, 25));

        employee_details_label.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        employee_details_label.setForeground(new java.awt.Color(51, 51, 255));
        employee_details_label.setText("Employee Details");
        pay_mgt_panel.add(employee_details_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 25, 296, -1));

        emp_namelbl1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        emp_namelbl1.setForeground(new java.awt.Color(0, 0, 255));
        emp_namelbl1.setText("Employee Name");
        pay_mgt_panel.add(emp_namelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 102, 121, 25));

        emp_name_payroll.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        pay_mgt_panel.add(emp_name_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 101, 334, 25));

        search_payroll.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        search_payroll.setForeground(new java.awt.Color(51, 51, 255));
        search_payroll.setText("Search");
        search_payroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_payrollMouseClicked(evt);
            }
        });
        pay_mgt_panel.add(search_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 68, -1, -1));

        emp_positionlbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        emp_positionlbl.setForeground(new java.awt.Color(0, 0, 255));
        emp_positionlbl.setText("Employee Position/Department");
        pay_mgt_panel.add(emp_positionlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 132, -1, 25));

        emp_position_payroll.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        pay_mgt_panel.add(emp_position_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 131, 259, 25));

        start_datelbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        start_datelbl.setForeground(new java.awt.Color(0, 0, 255));
        start_datelbl.setText("Period Start Date");
        pay_mgt_panel.add(start_datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 208, 121, 25));

        start_date_payroll.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        pay_mgt_panel.add(start_date_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 207, 274, 25));

        end_datelbl3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        end_datelbl3.setForeground(new java.awt.Color(0, 0, 255));
        end_datelbl3.setText("Period End Date");
        pay_mgt_panel.add(end_datelbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 246, 121, 25));

        end_date_payroll.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        pay_mgt_panel.add(end_date_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 245, 274, 25));

        payslip_details_label.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        payslip_details_label.setForeground(new java.awt.Color(51, 51, 255));
        payslip_details_label.setText("Payslip Details");
        pay_mgt_panel.add(payslip_details_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 169, 293, -1));

        benefits_lable.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        benefits_lable.setForeground(new java.awt.Color(51, 51, 255));
        benefits_lable.setText("Benefits");
        pay_mgt_panel.add(benefits_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 277, 293, -1));

        end_datelbl4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        end_datelbl4.setForeground(new java.awt.Color(0, 0, 255));
        end_datelbl4.setText("Rice Subsidy");
        pay_mgt_panel.add(end_datelbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 317, 121, 25));

        rice_payroll.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(rice_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 317, 149, 25));

        phone_allow_label.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        phone_allow_label.setForeground(new java.awt.Color(0, 0, 255));
        phone_allow_label.setText("Phone Allowance");
        pay_mgt_panel.add(phone_allow_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 348, 121, 25));

        phone_payroll.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(phone_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 348, 149, 25));

        clothing_lbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        clothing_lbl.setForeground(new java.awt.Color(0, 0, 255));
        clothing_lbl.setText("Clothing Allowance");
        pay_mgt_panel.add(clothing_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 379, 126, 25));

        cloth_payroll.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(cloth_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 379, 149, 25));

        benefits_lable1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        benefits_lable1.setForeground(new java.awt.Color(51, 51, 255));
        benefits_lable1.setText("Salary Details");
        pay_mgt_panel.add(benefits_lable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 143, -1));

        monthly_ratelbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        monthly_ratelbl.setForeground(new java.awt.Color(0, 0, 255));
        monthly_ratelbl.setText("Monthly Rate");
        pay_mgt_panel.add(monthly_ratelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 121, 25));

        monthly_rate_payroll.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(monthly_rate_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 149, 25));

        semi_ratelbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        semi_ratelbl.setForeground(new java.awt.Color(0, 0, 255));
        semi_ratelbl.setText("Semi-monthly Rate");
        pay_mgt_panel.add(semi_ratelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 121, 25));

        semi_rate_payroll.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(semi_rate_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 149, 25));

        daily_ratelbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        daily_ratelbl.setForeground(new java.awt.Color(0, 0, 255));
        daily_ratelbl.setText("Daily Rate");
        pay_mgt_panel.add(daily_ratelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 126, 25));

        daily_rate_payroll.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(daily_rate_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 149, 25));

        total_ben_label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        total_ben_label.setForeground(new java.awt.Color(0, 0, 255));
        total_ben_label.setText("Total");
        pay_mgt_panel.add(total_ben_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 410, 126, 25));

        total_ben_payroll.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        total_ben_payroll.setForeground(new java.awt.Color(0, 51, 204));
        pay_mgt_panel.add(total_ben_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 410, 149, 25));

        days_workedlbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        days_workedlbl.setForeground(new java.awt.Color(0, 0, 255));
        days_workedlbl.setText("Days Worked");
        pay_mgt_panel.add(days_workedlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 126, 25));

        days_worked_payroll.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(days_worked_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 149, 25));

        overtime_lbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        overtime_lbl.setForeground(new java.awt.Color(0, 0, 255));
        overtime_lbl.setText("Overtime");
        pay_mgt_panel.add(overtime_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 126, 25));

        overtime_payroll.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        overtime_payroll.setText("0");
        pay_mgt_panel.add(overtime_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 149, 25));

        gross_label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        gross_label.setForeground(new java.awt.Color(0, 0, 255));
        gross_label.setText("Gross Income");
        pay_mgt_panel.add(gross_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 126, 25));

        total_deduct_label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        total_deduct_label.setForeground(new java.awt.Color(0, 0, 255));
        total_deduct_label.setText("Total");
        pay_mgt_panel.add(total_deduct_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 633, 126, 25));

        total_deduct_payroll.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        total_deduct_payroll.setForeground(new java.awt.Color(0, 51, 204));
        pay_mgt_panel.add(total_deduct_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 633, 149, 25));

        tax_payroll.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(tax_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 602, 149, 25));

        tax_label.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tax_label.setForeground(new java.awt.Color(0, 0, 255));
        tax_label.setText("Withholding Tax");
        pay_mgt_panel.add(tax_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 602, 126, 25));

        phil_label.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        phil_label.setForeground(new java.awt.Color(0, 0, 255));
        phil_label.setText("Philhealth");
        pay_mgt_panel.add(phil_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 542, 121, 25));

        phil_payroll.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(phil_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 542, 149, 25));

        sss_payroll.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(sss_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 511, 149, 25));

        sss_label.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        sss_label.setForeground(new java.awt.Color(0, 0, 255));
        sss_label.setText("Social Security System");
        pay_mgt_panel.add(sss_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 511, 121, 25));

        benefits_lable2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        benefits_lable2.setForeground(new java.awt.Color(51, 51, 255));
        benefits_lable2.setText("Deductions");
        pay_mgt_panel.add(benefits_lable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 485, 293, -1));

        calcu_Netpay.setForeground(new java.awt.Color(51, 51, 255));
        calcu_Netpay.setText("Calculate");
        calcu_Netpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcu_NetpayActionPerformed(evt);
            }
        });
        pay_mgt_panel.add(calcu_Netpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 530, -1, 25));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Time In", "Time In", "Hours Worked"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        pay_mgt_panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 25, -1, 246));

        benefits_lable3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        benefits_lable3.setForeground(new java.awt.Color(51, 51, 255));
        benefits_lable3.setText("Summary");
        pay_mgt_panel.add(benefits_lable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 293, -1));

        end_datelbl6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        end_datelbl6.setForeground(new java.awt.Color(0, 0, 255));
        end_datelbl6.setText("Gross Income");
        pay_mgt_panel.add(end_datelbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 121, 25));

        gross_inc_payroll_sum.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(gross_inc_payroll_sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, 149, 25));

        phone_allow_label2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        phone_allow_label2.setForeground(new java.awt.Color(0, 0, 255));
        phone_allow_label2.setText("Benifits");
        pay_mgt_panel.add(phone_allow_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 121, 25));

        total_ben_payroll_sum.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(total_ben_payroll_sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, 149, 25));

        clothing_lbl4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        clothing_lbl4.setForeground(new java.awt.Color(0, 0, 255));
        clothing_lbl4.setText("Deductions");
        pay_mgt_panel.add(clothing_lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 126, 25));

        total_deduct_payroll_sum.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(total_deduct_payroll_sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 460, 149, 25));

        clothing_lbl5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        clothing_lbl5.setForeground(new java.awt.Color(0, 0, 255));
        clothing_lbl5.setText("Net Pay");
        pay_mgt_panel.add(clothing_lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, 126, 25));

        net_pay.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        net_pay.setForeground(new java.awt.Color(0, 51, 204));
        pay_mgt_panel.add(net_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, 149, 25));

        benefits_lable4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        benefits_lable4.setForeground(new java.awt.Color(51, 51, 255));
        benefits_lable4.setText("Government Statutory");
        pay_mgt_panel.add(benefits_lable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 448, 293, -1));

        pag_ibig_label.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pag_ibig_label.setForeground(new java.awt.Color(0, 0, 255));
        pag_ibig_label.setText("Pag-ibig");
        pay_mgt_panel.add(pag_ibig_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 571, 126, 25));

        pag_ibig_payroll.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(pag_ibig_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 571, 149, 25));

        benefits_lable5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        benefits_lable5.setForeground(new java.awt.Color(51, 51, 255));
        benefits_lable5.setText("Employer Contribution");
        pay_mgt_panel.add(benefits_lable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 293, -1));

        pag_ibig_payroll_comp.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(pag_ibig_payroll_comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 149, 25));

        pag_ibig_payroll_comp_label.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pag_ibig_payroll_comp_label.setForeground(new java.awt.Color(0, 0, 255));
        pag_ibig_payroll_comp_label.setText("Pag-ibig");
        pay_mgt_panel.add(pag_ibig_payroll_comp_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 121, 25));

        phil_label1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        phil_label1.setForeground(new java.awt.Color(0, 0, 255));
        phil_label1.setText("Philhealth");
        pay_mgt_panel.add(phil_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, 121, 25));

        phil_payroll1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pay_mgt_panel.add(phil_payroll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, 149, 25));

        gross_inc_payroll.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        gross_inc_payroll.setForeground(new java.awt.Color(0, 51, 204));
        pay_mgt_panel.add(gross_inc_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 149, -1));
        pay_mgt_panel.add(twh_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(1178, 277, 100, -1));

        jLabel28.setBackground(new java.awt.Color(51, 51, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 255));
        jLabel28.setText("Total Working Days");
        pay_mgt_panel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 310, 110, 20));

        jLabel29.setBackground(new java.awt.Color(51, 51, 255));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 255));
        jLabel29.setText("Total Days Worked");
        pay_mgt_panel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 280, -1, -1));
        pay_mgt_panel.add(tdw_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 277, 100, -1));
        pay_mgt_panel.add(twd_payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 310, 100, -1));

        jLabel30.setBackground(new java.awt.Color(51, 51, 255));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 255));
        jLabel30.setText("Total Worked Hours");
        pay_mgt_panel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 280, -1, -1));

        page_panel.add(pay_mgt_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 770));

        rep_mgt_panel.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout rep_mgt_panelLayout = new javax.swing.GroupLayout(rep_mgt_panel);
        rep_mgt_panel.setLayout(rep_mgt_panelLayout);
        rep_mgt_panelLayout.setHorizontalGroup(
            rep_mgt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        rep_mgt_panelLayout.setVerticalGroup(
            rep_mgt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        page_panel.add(rep_mgt_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 780));

        bgmain.add(page_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1330, 770));

        getContentPane().add(bgmain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emp_mgtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_mgtMouseClicked
        // show Payroll Management Page
            //Change color when click
            setColor(emp_mgt);
            resetColor(pay_mgt);
            resetColor(rep_mgt);
            emp_mgt_panel.setVisible(true);
            pay_mgt_panel.setVisible(false);
            rep_mgt_panel.setVisible(false);
            
            
    }//GEN-LAST:event_emp_mgtMouseClicked

    private void pay_mgtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pay_mgtMouseClicked
        // show Payroll Management Page
            //Change color when click
            resetColor(emp_mgt);
            setColor(pay_mgt);
            resetColor(rep_mgt);
            emp_mgt_panel.setVisible(false);
            pay_mgt_panel.setVisible(true);
            rep_mgt_panel.setVisible(false);

    }//GEN-LAST:event_pay_mgtMouseClicked

    private void rep_mgtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rep_mgtMouseClicked
        // show Reports Management Page
            //Change color when click
            resetColor(emp_mgt);
            resetColor(pay_mgt);
            setColor(rep_mgt);
            //show panel
            emp_mgt_panel.setVisible(false);
            pay_mgt_panel.setVisible(false);
            rep_mgt_panel.setVisible(true);
        
    }//GEN-LAST:event_rep_mgtMouseClicked

    private void exit_onadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_onadminMouseClicked
        // Close app
        
        System.exit(0);
        
    }//GEN-LAST:event_exit_onadminMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseClicked
        // Update data:
        
        PreparedStatement st;
        ResultSet rst;

        //get employee ID
        
        String user = emp_no_pay.getText();
        String f_name = f_name_no_pay.getText();
        String l_name = l_name_no_pay.getText();
        String bday = bday_no_pay.getText();
        String address = address_no_pay.getText();
        String phone = phone_no_pay.getText();
        String sss = sss_no_pay.getText();
        String phil = phil_no_pay.getText();
        String tin = tin_no_pay.getText();
        String hdmf = hdmf_no_pay.getText();
        String status = status_no_pay.getText();
        String position = position_no_pay.getText();
        String sup = sup_no_pay.getText();
        String basic = basic_no_pay.getText();
        String rice = rice_no_pay.getText();
        String phone_allow = phone_allow_no_pay.getText();
        String cloth = cloth_no_pay.getText();
        String gross = gross_no_pay.getText();
        String hourly = hourly_no_pay.getText();
        
        
        
        //create a select query to pull data from employee database
        String query = "SELECT * FROM motorphemployeedb.`motorphemployeedata-employeedetails` WHERE  `Employee_no` = ? AND `Last_Name` = ? AND `First_Name` = ? AND `birthdate` = ? AND `Address` = ? AND `Phone_Number` = ? AND `SSS_no` = ? AND `Philhealth_no` = ? AND `TIN_no` = ? AND `Pag_ibig_no` = ? AND `Status` = ? AND `Position` = ? AND `Immediate_Supervisor` = ? AND `Basic_Salary` = ? AND `Rice_Subsidy` = ? AND `Phone_Allowance` = ? AND `Clothing_Allowance` = ? AND `Gross_Semi_monthly_Rate` = ? AND `Hourly_Rate` = ?";
        //create a select query to pull data from attendance database

        
        try{
            st = (PreparedStatement) db.getConnection().prepareStatement(query);

            st.setString(1,user);
            st.setString(2,l_name);
            st.setString(3,f_name);
            st.setString(4,bday);
            st.setString(5,address);
            st.setString(6,phone);
            st.setString(7,sss);
            st.setString(8,phil);
            st.setString(9,tin);
            st.setString(10,hdmf);
            st.setString(11,status);
            st.setString(12,position);
            st.setString(13,sup);
            st.setString(14,basic);
            st.setString(15,rice);
            st.setString(16,phone_allow);
            st.setString(17,cloth);
            st.setString(18,gross);
            st.setString(19,hourly);
            
            
            rst = st.executeQuery();
           

            if(rst.next()){
                
                
                JOptionPane.showMessageDialog(this,"You data already exist.");
                
                }else{
                

                        String user1 = emp_no_pay.getText();
                        String f_name1 = f_name_no_pay.getText();
                        String l_name1 = l_name_no_pay.getText();
                        String bday1 = bday_no_pay.getText();
                        String address1 = address_no_pay.getText();
                        String phone1 = phone_no_pay.getText();
                        String sss1 = sss_no_pay.getText();
                        String phil1 = phil_no_pay.getText();
                        String tin1 = tin_no_pay.getText();
                        String hdmf1 = hdmf_no_pay.getText();
                        String status1 = status_no_pay.getText();
                        String position1 = position_no_pay.getText();
                        String sup1 = sup_no_pay.getText();
                        String basic1 = basic_no_pay.getText();
                        String rice1 = rice_no_pay.getText();
                        String phone1_allow = phone_allow_no_pay.getText();
                        String cloth1 = cloth_no_pay.getText();
                        String gross1 = gross_no_pay.getText();
                        String hourly1 = hourly_no_pay.getText();
                
                
                
                String sql = "Update motorphemployeedb.`motorphemployeedata-employeedetails` SET Last_Name = ?,First_Name = ?,birthdate = ?, Address = ?, Phone_Number = ?, SSS_no = ?, Philhealth_no = ?,  TIN_no = ?, Pag_ibig_no = ?, Status = ?, Position = ?, Immediate_Supervisor = ?, Basic_Salary = ?, Rice_Subsidy = ?, Phone_Allowance = ?, Clothing_Allowance = ?, Gross_Semi_monthly_Rate = ?, Hourly_Rate = ? WHERE Employee_no = ?";  

                
                try (PreparedStatement statement = db.getConnection().prepareStatement(sql)){  
                     
             
                    statement.setString(1,l_name1);
                    statement.setString(2,f_name1);
                    statement.setString(3,bday1);
                    statement.setString(4,address1);
                    statement.setString(5,phone1);
                    statement.setString(6,sss1);
                    statement.setString(7,phil1);
                    statement.setString(8,tin1);
                    statement.setString(9,hdmf1);
                    statement.setString(10,status1);
                    statement.setString(11,position1);
                    statement.setString(12,sup1);
                    statement.setString(13,basic1);
                    statement.setString(14,rice1);
                    statement.setString(15,phone1_allow);
                    statement.setString(16,cloth1);
                    statement.setString(17,gross1);
                    statement.setString(18,hourly1);
                    statement.setString(19,user1);
                    statement.executeUpdate();
                   
                }
                
                JOptionPane.showMessageDialog(this,"You're data has been updated. Thank you!");
                
                load_data_empdb();
                
                        emp_no_pay.setText("");
                        f_name_no_pay.setText("");
                        l_name_no_pay.setText("");
                        bday_no_pay.setText("");
                        address_no_pay.setText("");
                        phone_no_pay.setText("");
                        sss_no_pay.setText("");
                        phil_no_pay.setText("");
                        tin_no_pay.setText("");
                        hdmf_no_pay.setText("");
                        status_no_pay.setText("");
                        position_no_pay.setText("");
                        sup_no_pay.setText("");
                        basic_no_pay.setText("");
                        rice_no_pay.setText("");
                        phone_allow_no_pay.setText("");
                        cloth_no_pay.setText("");
                        gross_no_pay.setText("");
                        hourly_no_pay.setText("");

            }
            
            
        } catch (HeadlessException | SQLException e) {
            Logger.getLogger(AdminPayroll.class.getName()).log(Level.SEVERE, null, e);
        }
        
        
    }//GEN-LAST:event_btn_updateMouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        // Search Employee:
        
        PreparedStatement st;
        ResultSet rs;

        
        
        //get employee ID
        String user = emp_no_pay.getText();
        
        //create a select query to pull data from employee database
        String query = "SELECT * FROM motorphemployeedb.`motorphemployeedata-employeedetails` WHERE `Employee_no` = ?";
        //create a select query to pull data from attendance database

        
        try{
            st = (PreparedStatement) db.getConnection().prepareStatement(query);
            st.setString(1,user);
            
            rs = st.executeQuery();
           

            while(rs.next()){
                
                //employee
                l_name_no_pay.setText(rs.getString(2));
                f_name_no_pay.setText(rs.getString(3));
                position_no_pay.setText(rs.getString(12));
                sup_no_pay.setText(rs.getString(13));
                
                //Employee details
                address_no_pay.setText(rs.getString(5));
                status_no_pay.setText(rs.getString(11));
                bday_no_pay.setText(rs.getString(4));
                phone_no_pay.setText(rs.getString(6));
                
                
                //Employee Gov details
                
//                acctno_info.setText(rs.getString(6));
                tin_no_pay.setText(rs.getString(9));
                hdmf_no_pay.setText(rs.getString(10));
                sss_no_pay.setText(rs.getString(7));
                phil_no_pay.setText(rs.getString(8));
                
               
                //benefits
                basic_no_pay.setText(rs.getString(14));
                gross_no_pay.setText(rs.getString(18));
                hourly_no_pay.setText(rs.getString(19));
                rice_no_pay.setText(rs.getString(15));
                phone_allow_no_pay.setText(rs.getString(16));
                cloth_no_pay.setText(rs.getString(17));
                     

            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPayroll.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btn_searchMouseClicked

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // Clear:
        
                        emp_no_pay.setText("");
                        f_name_no_pay.setText("");
                        l_name_no_pay.setText("");
                        bday_no_pay.setText("");
                        address_no_pay.setText("");
                        phone_no_pay.setText("");
                        sss_no_pay.setText("");
                        phil_no_pay.setText("");
                        tin_no_pay.setText("");
                        hdmf_no_pay.setText("");
                        status_no_pay.setText("");
                        position_no_pay.setText("");
                        sup_no_pay.setText("");
                        basic_no_pay.setText("");
                        rice_no_pay.setText("");
                        phone_allow_no_pay.setText("");
                        cloth_no_pay.setText("");
                        gross_no_pay.setText("");
                        hourly_no_pay.setText("");
                        
                        auto_increment_empdb();
        
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // Save
        
        PreparedStatement st;
        ResultSet rst;

        //get employee ID
        
        String user = emp_no_pay.getText();
        String f_name = f_name_no_pay.getText();
        String l_name = l_name_no_pay.getText();
//        String bday = bday_no_pay.getText();
//        String address = address_no_pay.getText();
//        String phone = phone_no_pay.getText();
//        String sss = sss_no_pay.getText();
//        String phil = phil_no_pay.getText();
//        String tin = tin_no_pay.getText();
//        String hdmf = hdmf_no_pay.getText();
//        String status = status_no_pay.getText();
//        String position = position_no_pay.getText();
//        String sup = sup_no_pay.getText();
//        String basic = basic_no_pay.getText();
//        String rice = rice_no_pay.getText();
//        String phone_allow = phone_allow_no_pay.getText();
//        String cloth = cloth_no_pay.getText();
//        String gross = gross_no_pay.getText();
//        String hourly = hourly_no_pay.getText();
        
        
        
        //create a select query to pull data from employee database
        String query = "SELECT * FROM motorphemployeedb.`motorphemployeedata-employeedetails` WHERE  `Employee_no` = ? AND `Last_Name` = ? AND `First_Name` = ?";
        //create a select query to pull data from attendance database

        
        try{
            st = (PreparedStatement) db.getConnection().prepareStatement(query);

            st.setString(1,user);
            st.setString(2,l_name);
            st.setString(3,f_name);

            
            
            rst = st.executeQuery();
           

            if(rst.next()){
                
                
                JOptionPane.showMessageDialog(this,"You data already exist.");
                
                }else{
                
                    
                        String user1 = emp_no_pay.getText();
                        String f_name1 = f_name_no_pay.getText();
                        String l_name1 = l_name_no_pay.getText();
                        String bday1 = bday_no_pay.getText();
                        String address1 = address_no_pay.getText();
                        String phone1 = phone_no_pay.getText();
                        String sss1 = sss_no_pay.getText();
                        String phil1 = phil_no_pay.getText();
                        String tin1 = tin_no_pay.getText();
                        String hdmf1 = hdmf_no_pay.getText();
                        String status1 = status_no_pay.getText();
                        String position1 = position_no_pay.getText();
                        String sup1 = sup_no_pay.getText();
                        String basic1 = basic_no_pay.getText();
                        String rice1 = rice_no_pay.getText();
                        String phone1_allow = phone_allow_no_pay.getText();
                        String cloth1 = cloth_no_pay.getText();
                        String gross1 = gross_no_pay.getText();
                        String hourly1 = hourly_no_pay.getText();
                
                
                
                            String sql = "INSERT INTO motorphemployeedb.`motorphemployeedata-employeedetails` (Employee_no,Last_Name,First_Name,birthdate, Address, Phone_Number, SSS_no, Philhealth_no, TIN_no, Pag_ibig_no, Status, Position, Immediate_Supervisor, Basic_Salary, Rice_Subsidy, Phone_Allowance, Clothing_Allowance, Gross_Semi_monthly_Rate, Hourly_Rate) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";  


                            try (PreparedStatement statement = db.getConnection().prepareStatement(sql)){  


                                statement.setString(1,user1);
                                statement.setString(2,l_name1);
                                statement.setString(3,f_name1);
                                statement.setString(4,bday1);
                                statement.setString(5,address1);
                                statement.setString(6,phone1);
                                statement.setString(7,sss1);
                                statement.setString(8,phil1);
                                statement.setString(9,tin1);
                                statement.setString(10,hdmf1);
                                statement.setString(11,status1);
                                statement.setString(12,position1);
                                statement.setString(13,sup1);
                                statement.setString(14,basic1);
                                statement.setString(15,rice1);
                                statement.setString(16,phone1_allow);
                                statement.setString(17,cloth1);
                                statement.setString(18,gross1);
                                statement.setString(19,hourly1);

                                statement.executeUpdate();

                            }

                        JOptionPane.showMessageDialog(this,"You're data has been saved.");

                            load_data_empdb();

                                emp_no_pay.setText("");
                                f_name_no_pay.setText("");
                                l_name_no_pay.setText("");
                                bday_no_pay.setText("");
                                address_no_pay.setText("");
                                phone_no_pay.setText("");
                                sss_no_pay.setText("");
                                phil_no_pay.setText("");
                                tin_no_pay.setText("");
                                hdmf_no_pay.setText("");
                                status_no_pay.setText("");
                                position_no_pay.setText("");
                                sup_no_pay.setText("");
                                basic_no_pay.setText("");
                                rice_no_pay.setText("");
                                phone_allow_no_pay.setText("");
                                cloth_no_pay.setText("");
                                gross_no_pay.setText("");
                                hourly_no_pay.setText("");
                            }

            
            
        } catch (HeadlessException | SQLException e) {
            Logger.getLogger(AdminPayroll.class.getName()).log(Level.SEVERE, null, e);
        }
        
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void search_payrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_payrollMouseClicked
        // TODO add your handling code here:
        
        
        PreparedStatement st;
        ResultSet rs;

        
        
        //get employee ID
        String user = emp_no_payroll.getText();
        
        //create a select query to pull data from employee database
        String query = "SELECT * FROM motorphemployeedb.`motorphemployeedata-employeedetails` WHERE `Employee_no` = ?";
        //create a select query to pull data from attendance database

        
        try{
            st = (PreparedStatement) db.getConnection().prepareStatement(query);
            st.setString(1,user);
            
            rs = st.executeQuery();
           

            while(rs.next()){
                
                emp_name_payroll.setText(rs.getString(2)+", "+rs.getString(3));

                emp_position_payroll.setText(rs.getString(12));
                
                monthly_rate_payroll.setText(convert(rs.getString(14)));
                rice_payroll.setText(convert(rs.getString(15)));
                phone_payroll.setText(convert(rs.getString(16)));
                cloth_payroll.setText(convert(rs.getString(17)));
                semi_rate_payroll.setText(convert(rs.getString(18)));
                
            
            
            }
            load_attendane_db();
            benefits_calculation();
            pagibig_calculation();
            philhealth_calculation();
            sss_calculation();
            gross_inc();

            tax_calculation();
            twh_payroll.setText(Integer.toString(total_hourswork()));
            total_dayswork();
            total_deduction ();
            
            twd_payroll.setText(Integer.toString(total_workingdays()));
            dailyrate_payroll();
            
        
        } catch (SQLException ex) {
            Logger.getLogger(AdminPayroll.class.getName()).log(Level.SEVERE, null, ex);
        }
   
        
    }//GEN-LAST:event_search_payrollMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        load_data_empdb();
        auto_increment_empdb();
        
    }//GEN-LAST:event_formWindowOpened

    private void calcu_NetpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcu_NetpayActionPerformed
        // TODO add your handling code here:
        
        double gross = Double.parseDouble(gross_inc_payroll_sum.getText());
        double ben = Double.parseDouble(total_ben_payroll_sum.getText());
        double deduct = Double.parseDouble(total_deduct_payroll_sum.getText());
        
        net_pay.setText(Double.toString((gross+ben)-deduct));
        
    }//GEN-LAST:event_calcu_NetpayActionPerformed

    
    private int xMouse, yMouse;
    private void bgmainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgmainMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_bgmainMousePressed

    private void bgmainMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgmainMouseDragged
        // TODO add your handling code here:
        
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse);
        
    }//GEN-LAST:event_bgmainMouseDragged

    private void logout_onadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_onadminMouseClicked
        // TODO add your handling code here:
        this.dispose();
        SignIn sign= new SignIn();
        sign.setVisible(true);
        sign.pack();
        sign.setLocationRelativeTo(null);//Center
        
    }//GEN-LAST:event_logout_onadminMouseClicked

    
  
    
    
    
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(255,255,255)); 
    }
    
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(204,204,204)); 
    }
    

    private void load_data_empdb(){
        
        PreparedStatement st;
        ResultSet rs;
        
        String query = ("SELECT * FROM motorphemployeedb.`motorphemployeedata-employeedetails`");
        String[] columnNames = {"Employee Number","Employee Name","Birthday"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames,0);
        
        try{
            st = (PreparedStatement) db.getConnection().prepareStatement(query);
            
            
            rs = st.executeQuery();
           

            while(rs.next()){
            
              String Employee_no= rs.getString("Employee_no");
              String Employee_name= rs.getString("Last_Name") + ", " +rs.getString("First_Name");
              String Employee_bday= rs.getString("birthdate");
              
              
              // create a single array of one row's worth of data
                String[] data = { Employee_no, Employee_name, Employee_bday } ;

              // and add this row of data into the table model
              tableModel.addRow(data);
                
                


            }
            jTable1.setModel(tableModel); // place model into JTable
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminPayroll.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    private void auto_increment_empdb(){
        PreparedStatement st;
        ResultSet rs;
       
        
        //create a select query to pull data from employee database
        String query = "SELECT `Employee_no` FROM motorphemployeedb.`motorphemployeedata-employeedetails` ORDER BY `Employee_no` DESC LIMIT 1";
        
        try {
            
            st = (PreparedStatement) db.getConnection().prepareStatement(query);
           
            rs = st.executeQuery();
            
            if (rs.next()){
                
                int stamp =rs.getInt(1);
                int n = stamp+1;
                
                emp_no_pay.setText(Integer.toString(n)); 
                
            }
            
            
        }catch(Exception e){
            JOptionPane.showInputDialog(null,e);
        }
    }
    
    
    private void benefits_calculation(){
        
        int rice = Integer.parseInt(rice_payroll.getText());
        int phone = Integer.parseInt(phone_payroll.getText());
        int cloth = Integer.parseInt(cloth_payroll.getText());
        
        total_ben_payroll.setText(Integer.toString(rice+phone+cloth));
        total_ben_payroll_sum.setText(Integer.toString(rice+phone+cloth));
        
    }
    
    private void pagibig_calculation(){
        
        int salary = Integer.parseInt(monthly_rate_payroll.getText());
        double lowerbracket = 0.01*salary;
        double compbracket = 0.02*salary;
        
        if(salary<1000){
            pag_ibig_payroll.setText("0");
            pag_ibig_payroll_comp.setText("0");
            
        }else if(salary<=1500){    
            
            pag_ibig_payroll.setText(Double.toString(lowerbracket));
            pag_ibig_payroll_comp.setText(Double.toString(compbracket));
        

            
        }else{
            
            if (compbracket == 100 ){
                
                pag_ibig_payroll.setText(Double.toString(compbracket));
                pag_ibig_payroll_comp.setText(Double.toString(compbracket));

            
            }else{
                
                pag_ibig_payroll.setText("100");
                pag_ibig_payroll_comp.setText("100");
                
            }
        }
        
        
    }
    
    private void philhealth_calculation(){
        
        int salary = Integer.parseInt(monthly_rate_payroll.getText());
        double totalbracket = 0.03*salary;
        double bracket = totalbracket/2;
        
        boolean less = salary < 10000;


        if (less) {
            
            phil_payroll.setText("0");
            phil_payroll1.setText("0");
            
        }else{
            
            phil_payroll.setText(Double.toString(bracket));
            phil_payroll1.setText(Double.toString(bracket));
        
        }

         
    }
    
    
    private void sss_calculation(){
        
        int salary = Integer.parseInt(monthly_rate_payroll.getText());
        int forevery = salary/500;
        double incr = 22.50;
        
        if (salary<3250) {
            
            sss_payroll.setText("135");
            
        }else if (salary<24750){
            
            sss_payroll.setText(Double.toString(forevery*incr));
            
        }else{
            
            sss_payroll.setText("1125");
            
        }
        
    }
    
    
    private void gross_inc(){
        
        twh_payroll.setText(Integer.toString(total_hourswork()));
        twd_payroll.setText(Integer.toString(total_workingdays()));
        tdw_payroll.setText(Integer.toString(total_hourswork()/8));
        double dailyrate = (Integer.parseInt(monthly_rate_payroll.getText())) / Double.parseDouble(twd_payroll.getText());
        double workhours = Double.parseDouble(tdw_payroll.getText());
        double salary = dailyrate*workhours;
        double hourlyrate = dailyrate/8;
        double overtime = Double.parseDouble(overtime_payroll.getText());
        double overtimepay = hourlyrate*overtime;


        gross_inc_payroll.setText(Double.toString(salary+overtimepay));
        gross_inc_payroll_sum.setText(Double.toString(salary+overtimepay));
        
        
    }
    

    
    
    
    private void tax_calculation(){
        
        int salary = Integer.parseInt(monthly_rate_payroll.getText());
        
        double gross = Double.parseDouble(gross_inc_payroll.getText());
        double phil = Double.parseDouble(phil_payroll.getText());
        double sss = Double.parseDouble(sss_payroll.getText());
        double hdmf = Double.parseDouble(pag_ibig_payroll.getText());
        
        double sal = gross-phil-sss-hdmf;
        
        
        
        double first = 0.20*(20833-sal);
        double second = 0.25*(33333-sal);
        double third = 0.30*(66667-sal);
        double forth = 0.32*(166667-sal);
        double fifth = 0.35*(666667-sal);
        
        int se = 2500;
        int th = 10833;
        double fo = 40833.33;
        double fi = 200833.33;

        
        if(salary<20832){
            
            tax_payroll.setText("0");
            
        }else if(salary<33333){
            
            tax_payroll.setText(Double.toString(first));
            
        }else if(salary<66667){
            
            tax_payroll.setText(Double.toString(second+se));
        
        }else if(salary<166667){
            
            tax_payroll.setText(Double.toString(third+th));
            
        }else if(salary<666667){
            
            tax_payroll.setText(Double.toString(forth+fo));
            
        }else{
            tax_payroll.setText(Double.toString(fifth+fi));
        }
         
    }
    
    
    private void total_deduction (){
        
        double sss = Double.parseDouble(sss_payroll.getText());
        double pag_ibig = Double.parseDouble(pag_ibig_payroll.getText());
        double phil = Double.parseDouble(phil_payroll.getText());
        double tax = Double.parseDouble(tax_payroll.getText());
        
        total_deduct_payroll.setText(Double.toString(sss+pag_ibig+phil+tax));
        total_deduct_payroll_sum.setText(Double.toString(sss+pag_ibig+phil+tax));
  
        
    }
    
    
    private void load_attendane_db(){
        
        PreparedStatement st;
        ResultSet rs;

        
        int emp_no = Integer.parseInt(emp_no_payroll.getText());
        String user = Integer.toString(emp_no+10000);
        String start = start_date_payroll.getText();
        String end = end_date_payroll.getText();
        //get employee ID
        
        
        //create a select query to pull data from employee database
        String query = "SELECT * FROM motorphemployeedb.`attendance_record_test`WHERE `Employee_no` = ? AND `Date` BETWEEN ? AND ?";
        String[] columnNames = {"Date","Time In","Time Out","Hours Worked"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames,0);
        //create a select query to pull data from attendance database 

        
        try{
            st = (PreparedStatement) db.getConnection().prepareStatement(query);
            st.setString(1,user);
            st.setString(2,start);
            st.setString(3,end);
            
            rs = st.executeQuery();
           

            while(rs.next()){
            
              String  Date = rs.getString("date");
              String  Time_in= rs.getString("Time_in");
              String  Time_out= rs.getString("Time_out");
              
              
              // create a single array of one row's worth of data
                String[] data = { Date, Time_in, Time_out } ;

              // and add this row of data into the table model
              tableModel.addRow(data);
                


            }
            jTable2.setModel(tableModel); // place model into JTable
            
            workhours_calculation();
            
        } catch (SQLException ex) {
            Logger.getLogger(maindash.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    private void workhours_calculation(){
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm"); 
        SimpleDateFormat timeFormat = new SimpleDateFormat("H:mm");
         
       
        for (int i = 0; i < jTable2.getRowCount(); i++) {
             
           try {
               
               Date timeIn = dateFormat.parse(jTable2.getValueAt(i, 0)+" "+jTable2.getValueAt(i, 1));
               Date timeOut = dateFormat.parse(jTable2.getValueAt(i, 0)+" "+jTable2.getValueAt(i, 2));
               Date Login = timeFormat.parse("8:00");
               double check = (timeOut.getTime() - timeIn.getTime()) / (60.0 * 60.0 * 1000.0);
               
               if (check<=5){
                   
                   
                       int check2 = (int) ((timeOut.getTime() - timeIn.getTime()) / (60.0 * 60.0 * 1000.0));

                       switch(check2){
                           case 5: //halfday
                               int wh = (int) (check - 1);
                               jTable2.setValueAt(wh, i, 3);
                               break;
                           default://lessdan halfday
                               jTable2.setValueAt(check2, i, 3);
                               break;
                       } 
               }else if (check>=8.82){
                   
                   int lates= (int) ((timeIn.getTime() - Login.getTime()) / (60.0 * 60.0 * 1000.0));
                   
                  if(lates>=0){
                      int wh = (int) (8);
                               jTable2.setValueAt(wh, i, 3);
                  }else{ 
                      int wh = (int) (check - 1);
                               jTable2.setValueAt(wh, i, 3);
                  }        
               }else{
                   
                   int wh = (int) (check - 1);
                               jTable2.setValueAt(wh, i, 3);
                   
                   
               }
               
               
            } catch (ParseException ex) {
               Logger.getLogger(AdminPayroll.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }
 
    
    private int total_hourswork(){
        
        int sum = 0;
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            sum= sum+Integer.parseInt(jTable2.getValueAt(i, 3).toString());
        }
        return sum;
    }
    
    
    private void total_dayswork(){
        
        tdw_payroll.setText(Integer.toString(total_hourswork()/8));
        days_worked_payroll.setText(Integer.toString(total_hourswork()/8));
        
    }
    
    private int total_workingdays(){
        
        int sum = 0;
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            sum= sum+1;
        }
        return sum;
    }
    
    
    private void dailyrate_payroll(){
        
        int workingdays = Integer.parseInt(twd_payroll.getText());
        int monthsal = Integer.parseInt(monthly_rate_payroll.getText());
        
        daily_rate_payroll.setText(Integer.toString(monthsal/workingdays));
        
    }
    
    
    public static String convert(String str){
        
        
        StringBuffer sb = new StringBuffer(str);
        
        for(int i=0; i<sb.length();i++){
        
            if(sb.charAt(i)<48 || sb.charAt(i)>57){
            
                sb.deleteCharAt(i);
                
                i--;
                
            }
        }
         
        return sb.toString();
        
    }
    
    
    @SuppressWarnings("empty-statement")

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPayroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_no_pay;
    private javax.swing.JTextField basic_no_pay;
    private javax.swing.JTextField bday_no_pay;
    private javax.swing.JLabel benefits_lable;
    private javax.swing.JLabel benefits_lable1;
    private javax.swing.JLabel benefits_lable2;
    private javax.swing.JLabel benefits_lable3;
    private javax.swing.JLabel benefits_lable4;
    private javax.swing.JLabel benefits_lable5;
    private javax.swing.JPanel bgmain;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton calcu_Netpay;
    private javax.swing.JTextField cloth_no_pay;
    private javax.swing.JTextField cloth_payroll;
    private javax.swing.JLabel clothing_lbl;
    private javax.swing.JLabel clothing_lbl4;
    private javax.swing.JLabel clothing_lbl5;
    private javax.swing.JTextField daily_rate_payroll;
    private javax.swing.JLabel daily_ratelbl;
    private javax.swing.JTextField days_worked_payroll;
    private javax.swing.JLabel days_workedlbl;
    private javax.swing.JPanel emp_mgt;
    private javax.swing.JPanel emp_mgt_panel;
    private javax.swing.JTextField emp_name_payroll;
    private javax.swing.JLabel emp_namelbl1;
    private javax.swing.JTextField emp_no_pay;
    private javax.swing.JTextField emp_no_payroll;
    private javax.swing.JLabel emp_numberlbl;
    private javax.swing.JTextField emp_position_payroll;
    private javax.swing.JLabel emp_positionlbl;
    private javax.swing.JLabel employee_details_label;
    private javax.swing.JTextField end_date_payroll;
    private javax.swing.JLabel end_datelbl3;
    private javax.swing.JLabel end_datelbl4;
    private javax.swing.JLabel end_datelbl6;
    private javax.swing.JLabel exit_onadmin;
    private javax.swing.JTextField f_name_no_pay;
    private javax.swing.JTextField gross_inc_payroll;
    private javax.swing.JTextField gross_inc_payroll_sum;
    private javax.swing.JLabel gross_label;
    private javax.swing.JTextField gross_no_pay;
    private javax.swing.JTextField hdmf_no_pay;
    private javax.swing.JTextField hourly_no_pay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField l_name_no_pay;
    private javax.swing.JLabel logout_onadmin;
    private javax.swing.JTextField monthly_rate_payroll;
    private javax.swing.JLabel monthly_ratelbl;
    private javax.swing.JTextField net_pay;
    private javax.swing.JLabel overtime_lbl;
    private javax.swing.JTextField overtime_payroll;
    private javax.swing.JLabel pag_ibig_label;
    private javax.swing.JTextField pag_ibig_payroll;
    private javax.swing.JTextField pag_ibig_payroll_comp;
    private javax.swing.JLabel pag_ibig_payroll_comp_label;
    private javax.swing.JPanel page_panel;
    private javax.swing.JPanel pay_mgt;
    private javax.swing.JPanel pay_mgt_panel;
    private javax.swing.JLabel payslip_details_label;
    private javax.swing.JLabel phil_label;
    private javax.swing.JLabel phil_label1;
    private javax.swing.JTextField phil_no_pay;
    private javax.swing.JTextField phil_payroll;
    private javax.swing.JTextField phil_payroll1;
    private javax.swing.JLabel phone_allow_label;
    private javax.swing.JLabel phone_allow_label2;
    private javax.swing.JTextField phone_allow_no_pay;
    private javax.swing.JTextField phone_no_pay;
    private javax.swing.JTextField phone_payroll;
    private javax.swing.JTextField position_no_pay;
    private javax.swing.JPanel rep_mgt;
    private javax.swing.JPanel rep_mgt_panel;
    private javax.swing.JTextField rice_no_pay;
    private javax.swing.JTextField rice_payroll;
    private javax.swing.JButton search_payroll;
    private javax.swing.JTextField semi_rate_payroll;
    private javax.swing.JLabel semi_ratelbl;
    private javax.swing.JLabel sss_label;
    private javax.swing.JTextField sss_no_pay;
    private javax.swing.JTextField sss_payroll;
    private javax.swing.JTextField start_date_payroll;
    private javax.swing.JLabel start_datelbl;
    private javax.swing.JTextField status_no_pay;
    private javax.swing.JTextField sup_no_pay;
    private javax.swing.JLabel tax_label;
    private javax.swing.JTextField tax_payroll;
    private javax.swing.JTextField tdw_payroll;
    private javax.swing.JTextField tin_no_pay;
    private javax.swing.JPanel top_panel;
    private javax.swing.JLabel total_ben_label;
    private javax.swing.JTextField total_ben_payroll;
    private javax.swing.JTextField total_ben_payroll_sum;
    private javax.swing.JLabel total_deduct_label;
    private javax.swing.JTextField total_deduct_payroll;
    private javax.swing.JTextField total_deduct_payroll_sum;
    private javax.swing.JTextField twd_payroll;
    private javax.swing.JTextField twh_payroll;
    // End of variables declaration//GEN-END:variables
}
