/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.school.motorphpayroll;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author rashni alicand
 */
public class admin_payroll extends javax.swing.JFrame {

    /**
     * Creates new form admin_payroll
     */
    public admin_payroll() {
        initComponents();
    }

    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgmain = new javax.swing.JPanel();
        top_panel = new javax.swing.JPanel();
        emp_mgt = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rep_mgt = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pay_mgt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        exit_onadmin = new javax.swing.JLabel();
        logout_onadmin = new javax.swing.JLabel();
        page_panel = new javax.swing.JPanel();
        emp_mgt_panel = new javax.swing.JPanel();
        pay_mgt_panel = new javax.swing.JPanel();
        rep_mgt_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgmain.setBackground(new java.awt.Color(255, 255, 255));
        bgmain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top_panel.setBackground(new java.awt.Color(0, 51, 102));
        top_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emp_mgt.setBackground(new java.awt.Color(255, 255, 255));
        emp_mgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emp_mgtMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setLabelFor(emp_mgt);
        jLabel1.setText("Eployee Management");

        javax.swing.GroupLayout emp_mgtLayout = new javax.swing.GroupLayout(emp_mgt);
        emp_mgt.setLayout(emp_mgtLayout);
        emp_mgtLayout.setHorizontalGroup(
            emp_mgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emp_mgtLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        emp_mgtLayout.setVerticalGroup(
            emp_mgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emp_mgtLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        top_panel.add(emp_mgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 230, 50));

        rep_mgt.setBackground(new java.awt.Color(204, 204, 204));
        rep_mgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rep_mgtMouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setLabelFor(rep_mgt);
        jLabel3.setText("Reports Management");

        javax.swing.GroupLayout rep_mgtLayout = new javax.swing.GroupLayout(rep_mgt);
        rep_mgt.setLayout(rep_mgtLayout);
        rep_mgtLayout.setHorizontalGroup(
            rep_mgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rep_mgtLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        rep_mgtLayout.setVerticalGroup(
            rep_mgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rep_mgtLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );

        top_panel.add(rep_mgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 210, 50));

        pay_mgt.setBackground(new java.awt.Color(204, 204, 204));
        pay_mgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pay_mgtMouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setLabelFor(pay_mgt);
        jLabel2.setText("Payroll Management");

        javax.swing.GroupLayout pay_mgtLayout = new javax.swing.GroupLayout(pay_mgt);
        pay_mgt.setLayout(pay_mgtLayout);
        pay_mgtLayout.setHorizontalGroup(
            pay_mgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pay_mgtLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(49, 49, 49))
        );
        pay_mgtLayout.setVerticalGroup(
            pay_mgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pay_mgtLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18))
        );

        top_panel.add(pay_mgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 210, 50));

        exit_onadmin.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        exit_onadmin.setForeground(new java.awt.Color(204, 0, 0));
        exit_onadmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_onadmin.setText("X");
        exit_onadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_onadminMouseClicked(evt);
            }
        });
        top_panel.add(exit_onadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, -1, -1));

        logout_onadmin.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        logout_onadmin.setForeground(new java.awt.Color(255, 255, 255));
        logout_onadmin.setText("Log out");
        top_panel.add(logout_onadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 60, -1));

        bgmain.add(top_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 80));

        page_panel.setBackground(new java.awt.Color(0, 102, 102));
        page_panel.setForeground(new java.awt.Color(0, 102, 102));
        page_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emp_mgt_panel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout emp_mgt_panelLayout = new javax.swing.GroupLayout(emp_mgt_panel);
        emp_mgt_panel.setLayout(emp_mgt_panelLayout);
        emp_mgt_panelLayout.setHorizontalGroup(
            emp_mgt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        emp_mgt_panelLayout.setVerticalGroup(
            emp_mgt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        page_panel.add(emp_mgt_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 760));

        javax.swing.GroupLayout pay_mgt_panelLayout = new javax.swing.GroupLayout(pay_mgt_panel);
        pay_mgt_panel.setLayout(pay_mgt_panelLayout);
        pay_mgt_panelLayout.setHorizontalGroup(
            pay_mgt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        pay_mgt_panelLayout.setVerticalGroup(
            pay_mgt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        page_panel.add(pay_mgt_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 810));

        rep_mgt_panel.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout rep_mgt_panelLayout = new javax.swing.GroupLayout(rep_mgt_panel);
        rep_mgt_panel.setLayout(rep_mgt_panelLayout);
        rep_mgt_panelLayout.setHorizontalGroup(
            rep_mgt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        rep_mgt_panelLayout.setVerticalGroup(
            rep_mgt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        page_panel.add(rep_mgt_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 780));

        bgmain.add(page_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1330, 770));

        getContentPane().add(bgmain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emp_mgtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_mgtMouseClicked
        // show Payroll Management Page
            //Change color when click
            setColor(emp_mgt);
            resetColor(pay_mgt);
            resetColor(rep_mgt);
            emp_mgt_panel.setVisible(true);
            pay_mgt_panel.setVisible(false);
            rep_mgt_panel.setVisible(false);
            
            
    }//GEN-LAST:event_emp_mgtMouseClicked

    private void pay_mgtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pay_mgtMouseClicked
        // show Payroll Management Page
            //Change color when click
            resetColor(emp_mgt);
            setColor(pay_mgt);
            resetColor(rep_mgt);
            emp_mgt_panel.setVisible(false);
            pay_mgt_panel.setVisible(true);
            rep_mgt_panel.setVisible(false);

    }//GEN-LAST:event_pay_mgtMouseClicked

    private void rep_mgtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rep_mgtMouseClicked
        // show Reports Management Page
            //Change color when click
            resetColor(emp_mgt);
            resetColor(pay_mgt);
            setColor(rep_mgt);
            //show panel
            emp_mgt_panel.setVisible(false);
            pay_mgt_panel.setVisible(false);
            rep_mgt_panel.setVisible(true);
        
    }//GEN-LAST:event_rep_mgtMouseClicked

    private void exit_onadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_onadminMouseClicked
        // Close app
        
        System.exit(0);
        
    }//GEN-LAST:event_exit_onadminMouseClicked

    
    void setColor(JPanel panel){
        panel.setBackground(new Color(255,255,255));
        
        
    }
    
    
    void resetColor(JPanel panel){
        
        panel.setBackground(new Color(204,204,204));
        
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_payroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgmain;
    private javax.swing.JPanel emp_mgt;
    private javax.swing.JPanel emp_mgt_panel;
    private javax.swing.JLabel exit_onadmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logout_onadmin;
    private javax.swing.JPanel page_panel;
    private javax.swing.JPanel pay_mgt;
    private javax.swing.JPanel pay_mgt_panel;
    private javax.swing.JPanel rep_mgt;
    private javax.swing.JPanel rep_mgt_panel;
    private javax.swing.JPanel top_panel;
    // End of variables declaration//GEN-END:variables
}
