/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.school.motorphpayroll;

import java.sql.Connection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.sql.DriverManager.getConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;






/**
 *
 * @author rashni alicand
 */
public class maindash extends javax.swing.JFrame {

    private Object rs;
    
    
    /**
     * Creates new form maindash
     */
    public maindash() {
        initComponents();
        
        datetime();
        
        
       
        
        
        
        
        
        
        
        
    }

    maindash(String username) { // get to main dash uthe username/employee ID
        
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        this();
        EmpID_num.setText(username);
        
    
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainDash = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_EmpInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_Time_Attend = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_Payslip = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        EmpInfoPanel = new javax.swing.JPanel();
        EmpName = new javax.swing.JLabel();
        EmpID = new javax.swing.JLabel();
        Comp_post = new javax.swing.JLabel();
        Department = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        add_info = new javax.swing.JLabel();
        empstatus_info = new javax.swing.JLabel();
        bday_info = new javax.swing.JLabel();
        phone_info = new javax.swing.JLabel();
        acctno_info = new javax.swing.JLabel();
        tin_info = new javax.swing.JLabel();
        hdmf_info = new javax.swing.JLabel();
        sss_info = new javax.swing.JLabel();
        phil_info = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        EmpID_num = new javax.swing.JLabel();
        compost_info = new javax.swing.JLabel();
        sup_info = new javax.swing.JLabel();
        Time_AttendPanel = new javax.swing.JPanel();
        name_time = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date_time = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        time_time = new javax.swing.JLabel();
        stamp_no = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        empid_time = new javax.swing.JLabel();
        clock_in = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        t_l_name = new javax.swing.JLabel();
        t_f_name = new javax.swing.JLabel();
        empID_t = new javax.swing.JLabel();
        PayslipPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        netPay = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ttlEarning = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        total_ben = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        ttlDeductions = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        payperiod = new javax.swing.JLabel();
        payoutdate = new javax.swing.JLabel();
        empid_payslip = new javax.swing.JLabel();
        payoutdate1 = new javax.swing.JLabel();
        rice_sum = new javax.swing.JLabel();
        cloth_sum = new javax.swing.JLabel();
        payoutdate4 = new javax.swing.JLabel();
        payoutdate7 = new javax.swing.JLabel();
        phone_sum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1276, 796));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainDash.setBackground(new java.awt.Color(255, 255, 255));
        MainDash.setPreferredSize(new java.awt.Dimension(1280, 800));
        MainDash.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MainDashMouseDragged(evt);
            }
        });
        MainDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MainDashMousePressed(evt);
            }
        });
        MainDash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(0, 102, 204));
        topPanel.setPreferredSize(new java.awt.Dimension(1280, 90));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(238, 0, 47));
        jLabel8.setText("x");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(96, 242, 0));
        jLabel1.setText("-");

        btn_EmpInfo.setBackground(new java.awt.Color(255, 255, 255));
        btn_EmpInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_EmpInfoMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Payroll Information");

        javax.swing.GroupLayout btn_EmpInfoLayout = new javax.swing.GroupLayout(btn_EmpInfo);
        btn_EmpInfo.setLayout(btn_EmpInfoLayout);
        btn_EmpInfoLayout.setHorizontalGroup(
            btn_EmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_EmpInfoLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(62, 62, 62))
        );
        btn_EmpInfoLayout.setVerticalGroup(
            btn_EmpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_EmpInfoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        btn_Time_Attend.setBackground(new java.awt.Color(204, 204, 204));
        btn_Time_Attend.setPreferredSize(new java.awt.Dimension(266, 78));
        btn_Time_Attend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Time_AttendMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Time & Attendance");

        javax.swing.GroupLayout btn_Time_AttendLayout = new javax.swing.GroupLayout(btn_Time_Attend);
        btn_Time_Attend.setLayout(btn_Time_AttendLayout);
        btn_Time_AttendLayout.setHorizontalGroup(
            btn_Time_AttendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_Time_AttendLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(28, 28, 28))
        );
        btn_Time_AttendLayout.setVerticalGroup(
            btn_Time_AttendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_Time_AttendLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        btn_Payslip.setBackground(new java.awt.Color(204, 204, 204));
        btn_Payslip.setPreferredSize(new java.awt.Dimension(266, 78));
        btn_Payslip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_PayslipMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Generate Payslip");

        javax.swing.GroupLayout btn_PayslipLayout = new javax.swing.GroupLayout(btn_Payslip);
        btn_Payslip.setLayout(btn_PayslipLayout);
        btn_PayslipLayout.setHorizontalGroup(
            btn_PayslipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_PayslipLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        btn_PayslipLayout.setVerticalGroup(
            btn_PayslipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_PayslipLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jLabel29.setBackground(new java.awt.Color(244, 244, 244));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(244, 244, 244));
        jLabel29.setText("Log Out");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_EmpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Time_Attend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Payslip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_EmpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Payslip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Time_Attend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MainDash.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 800));

        EmpInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        EmpInfoPanel.setPreferredSize(new java.awt.Dimension(1280, 800));

        EmpName.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        EmpName.setForeground(new java.awt.Color(51, 102, 255));
        EmpName.setText("Name of the Employee");

        EmpID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmpID.setForeground(new java.awt.Color(0, 102, 255));
        EmpID.setText("Employee ID");

        Comp_post.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Comp_post.setForeground(new java.awt.Color(0, 102, 255));
        Comp_post.setText("Position");

        Department.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Department.setForeground(new java.awt.Color(0, 102, 255));
        Department.setText("Immidiate Supervisor");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 2));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("Payroll Information");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 255));
        jLabel11.setText("Personal Information");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 255));
        jLabel12.setText("Address");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("Emp Status");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 255));
        jLabel14.setText("Birthdate");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 255));
        jLabel15.setText("Bank Account Number");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 255));
        jLabel16.setText("Phone number");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 255));
        jLabel17.setText("Tax Identification Number");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 255));
        jLabel18.setText("HDMF");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 255));
        jLabel19.setText("SSS");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 255));
        jLabel20.setText("PhilHealth");

        add_info.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        add_info.setForeground(new java.awt.Color(0, 102, 255));
        add_info.setText("Address");

        empstatus_info.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        empstatus_info.setForeground(new java.awt.Color(0, 102, 255));
        empstatus_info.setText("Empstatus");

        bday_info.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        bday_info.setForeground(new java.awt.Color(0, 102, 255));
        bday_info.setText("B-day");

        phone_info.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        phone_info.setForeground(new java.awt.Color(0, 102, 255));
        phone_info.setText("Phone");

        acctno_info.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        acctno_info.setForeground(new java.awt.Color(0, 102, 255));
        acctno_info.setText("Acct no");

        tin_info.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        tin_info.setForeground(new java.awt.Color(0, 102, 255));
        tin_info.setText("TIN");

        hdmf_info.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        hdmf_info.setForeground(new java.awt.Color(0, 102, 255));
        hdmf_info.setText("Pagibig");

        sss_info.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        sss_info.setForeground(new java.awt.Color(0, 102, 255));
        sss_info.setText("sss");

        phil_info.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        phil_info.setForeground(new java.awt.Color(0, 102, 255));
        phil_info.setText("Philh");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(phone_info, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_info, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empstatus_info, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bday_info, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phil_info, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sss_info, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hdmf_info, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tin_info, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(52, 52, 52)
                            .addComponent(acctno_info, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(210, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(add_info))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(empstatus_info))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(bday_info))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(phone_info))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(acctno_info))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tin_info))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(hdmf_info))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(sss_info))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(phil_info))
                .addGap(103, 103, 103))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel11)
                    .addContainerGap(514, Short.MAX_VALUE)))
        );

        jPanel5.setOpaque(false);

        jLabel30.setBackground(new java.awt.Color(31, 56, 100));
        jLabel30.setFont(new java.awt.Font("Segoe UI Black", 2, 60)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(31, 56, 100));
        jLabel30.setText("MotorPH");

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\rashni alicand\\Desktop\\Rash Tools\\MotorPH100.png")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(15, 15, 15))
        );

        EmpID_num.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        EmpID_num.setForeground(new java.awt.Color(0, 102, 255));
        EmpID_num.setText("Emp_ID");

        compost_info.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        compost_info.setForeground(new java.awt.Color(0, 102, 255));
        compost_info.setText("Position");

        sup_info.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        sup_info.setForeground(new java.awt.Color(0, 102, 255));
        sup_info.setText("Sup");

        javax.swing.GroupLayout EmpInfoPanelLayout = new javax.swing.GroupLayout(EmpInfoPanel);
        EmpInfoPanel.setLayout(EmpInfoPanelLayout);
        EmpInfoPanelLayout.setHorizontalGroup(
            EmpInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpInfoPanelLayout.createSequentialGroup()
                .addGroup(EmpInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpInfoPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(EmpInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EmpInfoPanelLayout.createSequentialGroup()
                                .addGroup(EmpInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Department)
                                    .addComponent(Comp_post, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(EmpInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmpID_num, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sup_info, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(compost_info, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        EmpInfoPanelLayout.setVerticalGroup(
            EmpInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpInfoPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(EmpInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmpInfoPanelLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(EmpName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EmpInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpID)
                            .addComponent(EmpID_num))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EmpInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Comp_post)
                            .addComponent(compost_info))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EmpInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Department)
                            .addComponent(sup_info)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        Time_AttendPanel.setBackground(new java.awt.Color(255, 255, 255));
        Time_AttendPanel.setPreferredSize(new java.awt.Dimension(1280, 518));

        name_time.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        name_time.setForeground(new java.awt.Color(51, 102, 255));
        name_time.setText("Last name, First name Middle initial.");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Schedule Logs");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setEnabled(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setForeground(new java.awt.Color(51, 51, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Acivity");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Todays' date:");

        date_time.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        date_time.setForeground(new java.awt.Color(51, 51, 255));
        date_time.setText("0");

        jLabel34.setForeground(new java.awt.Color(51, 51, 255));
        jLabel34.setText("Time");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time-in", "Time-out"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setEnabled(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        time_time.setFont(new java.awt.Font("Segoe UI", 2, 60)); // NOI18N
        time_time.setForeground(new java.awt.Color(0, 0, 255));
        time_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time_time.setText("00:00:00 A");

        stamp_no.setForeground(new java.awt.Color(242, 242, 242));
        stamp_no.setText("Stamp no");
        stamp_no.setFocusable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(time_time, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 45, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stamp_no)
                    .addComponent(jLabel34)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date_time, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(date_time))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addGap(17, 17, 17)
                .addComponent(time_time, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stamp_no)
                .addGap(91, 91, 91))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Schedule:");

        empid_time.setBackground(new java.awt.Color(255, 255, 255));
        empid_time.setForeground(new java.awt.Color(204, 204, 204));
        empid_time.setText("empid_time");
        empid_time.setFocusable(false);

        clock_in.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clock_in.setForeground(new java.awt.Color(51, 51, 255));
        clock_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clock_inMouseClicked(evt);
            }
        });

        jLabel31.setForeground(new java.awt.Color(0, 0, 255));
        jLabel31.setText("Clock-in");

        javax.swing.GroupLayout clock_inLayout = new javax.swing.GroupLayout(clock_in);
        clock_in.setLayout(clock_inLayout);
        clock_inLayout.setHorizontalGroup(
            clock_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clock_inLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel31)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        clock_inLayout.setVerticalGroup(
            clock_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clock_inLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel33.setForeground(new java.awt.Color(0, 0, 255));
        jLabel33.setText("Clock-out");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel33)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        t_l_name.setBackground(new java.awt.Color(255, 255, 255));
        t_l_name.setForeground(new java.awt.Color(255, 255, 255));
        t_l_name.setText("lastname");
        t_l_name.setFocusable(false);
        t_l_name.setRequestFocusEnabled(false);

        t_f_name.setBackground(new java.awt.Color(255, 255, 255));
        t_f_name.setForeground(new java.awt.Color(255, 255, 255));
        t_f_name.setText("jLabel36");
        t_f_name.setFocusable(false);
        t_f_name.setRequestFocusEnabled(false);

        empID_t.setForeground(new java.awt.Color(204, 204, 204));
        empID_t.setText("jLabel35");
        empID_t.setFocusable(false);

        javax.swing.GroupLayout Time_AttendPanelLayout = new javax.swing.GroupLayout(Time_AttendPanel);
        Time_AttendPanel.setLayout(Time_AttendPanelLayout);
        Time_AttendPanelLayout.setHorizontalGroup(
            Time_AttendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Time_AttendPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(Time_AttendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Time_AttendPanelLayout.createSequentialGroup()
                        .addGroup(Time_AttendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_time, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Time_AttendPanelLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(Time_AttendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Time_AttendPanelLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Time_AttendPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clock_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71))))
                            .addComponent(jLabel7))
                        .addContainerGap(93, Short.MAX_VALUE))
                    .addGroup(Time_AttendPanelLayout.createSequentialGroup()
                        .addGroup(Time_AttendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Time_AttendPanelLayout.createSequentialGroup()
                                .addComponent(t_l_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_f_name))
                            .addGroup(Time_AttendPanelLayout.createSequentialGroup()
                                .addComponent(empid_time)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empID_t)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Time_AttendPanelLayout.setVerticalGroup(
            Time_AttendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Time_AttendPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(name_time)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addGroup(Time_AttendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empid_time)
                    .addComponent(empID_t))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Time_AttendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Time_AttendPanelLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(Time_AttendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clock_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(Time_AttendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_l_name)
                    .addComponent(t_f_name))
                .addContainerGap())
        );

        PayslipPanel.setBackground(new java.awt.Color(255, 255, 255));
        PayslipPanel.setPreferredSize(new java.awt.Dimension(1280, 800));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 255));
        jLabel21.setText("Payroll Summary");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 255));
        jLabel22.setText("Net Pay:");

        netPay.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        netPay.setForeground(new java.awt.Color(51, 51, 255));
        netPay.setText("20,092.71");

        jLabel23.setBackground(new java.awt.Color(51, 63, 79));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Pay Period");
        jLabel23.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel23.setOpaque(true);

        jLabel24.setBackground(new java.awt.Color(51, 63, 79));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Pay-out Date");
        jLabel24.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel24.setOpaque(true);

        jLabel25.setBackground(new java.awt.Color(51, 63, 79));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Earnings:");
        jLabel25.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel25.setOpaque(true);

        ttlEarning.setBackground(new java.awt.Color(51, 63, 79));
        ttlEarning.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ttlEarning.setForeground(new java.awt.Color(255, 255, 255));
        ttlEarning.setText("32,123.35");
        ttlEarning.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ttlEarning.setOpaque(true);

        jLabel27.setBackground(new java.awt.Color(51, 63, 79));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Total Benefits:");
        jLabel27.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel27.setOpaque(true);

        total_ben.setBackground(new java.awt.Color(51, 63, 79));
        total_ben.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        total_ben.setForeground(new java.awt.Color(255, 255, 255));
        total_ben.setText("7800");
        total_ben.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        total_ben.setOpaque(true);

        jLabel26.setBackground(new java.awt.Color(51, 63, 79));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Total Deductions:");
        jLabel26.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel26.setOpaque(true);

        ttlDeductions.setBackground(new java.awt.Color(51, 63, 79));
        ttlDeductions.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ttlDeductions.setForeground(new java.awt.Color(255, 255, 255));
        ttlDeductions.setText("32,123.35");
        ttlDeductions.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ttlDeductions.setOpaque(true);

        jLabel28.setBackground(new java.awt.Color(51, 63, 79));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Pay-out Date");
        jLabel28.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel28.setOpaque(true);

        payperiod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        payperiod.setForeground(new java.awt.Color(51, 51, 255));
        payperiod.setText("Pay Period");

        payoutdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        payoutdate.setForeground(new java.awt.Color(51, 51, 255));
        payoutdate.setText("Pay-out Date");

        empid_payslip.setBackground(new java.awt.Color(255, 255, 255));
        empid_payslip.setForeground(new java.awt.Color(255, 255, 255));
        empid_payslip.setText("attendancedatabase");
        empid_payslip.setEnabled(false);

        payoutdate1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        payoutdate1.setForeground(new java.awt.Color(51, 51, 255));
        payoutdate1.setText("Rice Subsidy");

        rice_sum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rice_sum.setForeground(new java.awt.Color(51, 51, 255));
        rice_sum.setText("Rice");

        cloth_sum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cloth_sum.setForeground(new java.awt.Color(51, 51, 255));
        cloth_sum.setText("Cloth");

        payoutdate4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        payoutdate4.setForeground(new java.awt.Color(51, 51, 255));
        payoutdate4.setText("Phone Allownce");

        payoutdate7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        payoutdate7.setForeground(new java.awt.Color(51, 51, 255));
        payoutdate7.setText("Clothing Allowance");

        phone_sum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phone_sum.setForeground(new java.awt.Color(51, 51, 255));
        phone_sum.setText("Phone");

        javax.swing.GroupLayout PayslipPanelLayout = new javax.swing.GroupLayout(PayslipPanel);
        PayslipPanel.setLayout(PayslipPanelLayout);
        PayslipPanelLayout.setHorizontalGroup(
            PayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayslipPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(PayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PayslipPanelLayout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ttlDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PayslipPanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(netPay, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PayslipPanelLayout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ttlEarning, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PayslipPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_ben, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PayslipPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(payoutdate, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payperiod, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PayslipPanelLayout.createSequentialGroup()
                                .addComponent(payoutdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123)
                                .addComponent(rice_sum, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PayslipPanelLayout.createSequentialGroup()
                                .addGroup(PayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(payoutdate4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(payoutdate7, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cloth_sum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phone_sum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 1504, Short.MAX_VALUE))
            .addGroup(PayslipPanelLayout.createSequentialGroup()
                .addGroup(PayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PayslipPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel21))
                    .addGroup(PayslipPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(empid_payslip)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PayslipPanelLayout.setVerticalGroup(
            PayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayslipPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(empid_payslip)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(PayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(netPay))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payperiod)
                .addGap(7, 7, 7)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payoutdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(ttlEarning))
                .addGap(86, 86, 86)
                .addGroup(PayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(total_ben))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(payoutdate1)
                    .addComponent(rice_sum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payoutdate4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phone_sum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payoutdate7)
                    .addComponent(cloth_sum))
                .addGap(62, 62, 62)
                .addGroup(PayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(ttlDeductions))
                .addGap(87, 87, 87)
                .addComponent(jLabel28)
                .addGap(117, 117, 117))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmpInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Time_AttendPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PayslipPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(EmpInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 119, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(Time_AttendPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 112, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PayslipPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainDash.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        getContentPane().add(MainDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MousePressed

    private int xMouse,yMouse;
    private void MainDashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainDashMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_MainDashMousePressed

    private void MainDashMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainDashMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_MainDashMouseDragged

    private void btn_EmpInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpInfoMousePressed
        // TODO add your handling code here:
        setColor(btn_EmpInfo);
        resetColor(btn_Time_Attend);
        resetColor(btn_Payslip);
        EmpInfoPanel.setVisible(true);
        Time_AttendPanel.setVisible(false);
        PayslipPanel.setVisible(false);
    }//GEN-LAST:event_btn_EmpInfoMousePressed

    private void btn_Time_AttendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Time_AttendMousePressed
        // TODO add your handling code here:
        setColor(btn_Time_Attend);
        resetColor(btn_EmpInfo);
        resetColor(btn_Payslip);
        EmpInfoPanel.setVisible(false);
        Time_AttendPanel.setVisible(true);
        PayslipPanel.setVisible(false);
        
        timetime();
        load_table1();
        in_out_time();
        id_increment_time();
        
        
        //pull and show data
       
        
        
        
        
        
        
    }//GEN-LAST:event_btn_Time_AttendMousePressed

    private void btn_PayslipMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PayslipMousePressed
        // TODO add your handling code here:
        setColor(btn_Payslip);
        resetColor(btn_EmpInfo);
        resetColor(btn_Time_Attend);
        EmpInfoPanel.setVisible(false);
        Time_AttendPanel.setVisible(false);
        PayslipPanel.setVisible(true);
    }//GEN-LAST:event_btn_PayslipMousePressed

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        this.dispose();
        SignIn sign= new SignIn();
        sign.setVisible(true);
        sign.pack();
        sign.setLocationRelativeTo(null);//Center
    }//GEN-LAST:event_jLabel29MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet rs;

        
        
        //get employee ID
        String user = EmpID_num.getText();
        
        //create a select query to pull data from employee database
        String query = "SELECT * FROM motorphemployeedb.`motorphemployeedata-employeedetails` WHERE `Employee_#` = ?";
        //create a select query to pull data from attendance database

        
        try{
            st = (PreparedStatement) db.getConnection().prepareStatement(query);
            st.setString(1,user);
            
            rs = st.executeQuery();
           

            while(rs.next()){
                
                //employee
                EmpName.setText(rs.getString(2)+", "+rs.getString(3));
                compost_info.setText(rs.getString(12));
                sup_info.setText(rs.getString(13));
                
                //Employee details
                add_info.setText(rs.getString(5));
                empstatus_info.setText(rs.getString(11));
                bday_info.setText(rs.getString(4));
                phone_info.setText(rs.getString(6));
                
                
                //Employee Gov details
                
//                acctno_info.setText(rs.getString(6));
                tin_info.setText(rs.getString(9));
                hdmf_info.setText(rs.getString(10));
                sss_info.setText(rs.getString(7));
                phil_info.setText(rs.getString(8));
                
                
                
                //Attendance
                
                name_time.setText(rs.getString(2)+", "+rs.getString(3));
                t_f_name.setText(rs.getString(2));
                t_l_name.setText(rs.getString(3));
                empid_time.setText(rs.getString(1));
                empid_payslip.setText(rs.getString(1));
                
                
                //payslip
                
                //benefits
                rice_sum.setText(rs.getString(15));
                phone_sum.setText(rs.getString(16));
                cloth_sum.setText(rs.getString(17));
                     

            }
        } catch (SQLException ex) {
            Logger.getLogger(maindash.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void clock_inMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clock_inMouseClicked
        // Time in
        
        PreparedStatement st;
        ResultSet rst;
        empID_ti();

        //get employee ID
        
        String date_today = date_time.getText();
        String user = empID_t.getText();
        
        //create a select query to pull data from employee database
        String query = "SELECT * FROM motorphemployeedb.`attendance_record_test` WHERE `Date` = ? AND `Employee_no` = ?";
        //create a select query to pull data from attendance database

        
        try{
            st = (PreparedStatement) db.getConnection().prepareStatement(query);
            st.setString(1,date_today);
            st.setString(2,user);
            
            rst = st.executeQuery();
           

            if(rst.next()){
                
                
                JOptionPane.showMessageDialog(this,"You already clocked-in today.");
                
                }else{
                
//                JOptionPane.showMessageDialog(this,"before error");
                
                String stamp = stamp_no.getText();
                String datetoday = date_time.getText();
                String timetoday = time_time.getText();
                String f_name = t_f_name.getText();
                String l_name = t_l_name.getText();
                String empID = empID_t.getText();
                
//                String sql = "INSERT INTO motorphemployeedb.`attendance_record_test` (Stamp, Employee #, Last Name, First Name, Date, Time_in, Time_out) VALUES(?.?,?,?,?,?)";
                  String sql = "INSERT INTO motorphemployeedb.`attendance_record_test` (Stamp,Employee_no,Last_Name,First_Name,Date,Time_in) VALUES(?,?,?,?,?,?)";  
                  //,col2,col3,col4,col5,col6
                  //.?,?,?,?,?
                
                try (PreparedStatement statement = db.getConnection().prepareStatement(sql)){  
                     
              
                    statement.setString(1,stamp);
                    statement.setString(2,empID);
                    statement.setString(3,l_name);
                    statement.setString(4,f_name);
                    statement.setString(5,datetoday);
                    statement.setString(6,timetoday);
                    statement.executeUpdate();
                   
                }
                
                JOptionPane.showMessageDialog(this,"You're time-in has been recorded.>"
                        + "<Thank you!");
                
                load_table1();
                in_out_time();
                id_increment_time();
            }
            
        } catch (HeadlessException | SQLException e) {
            Logger.getLogger(maindash.class.getName()).log(Level.SEVERE, null, e);
        }
        
        
        
        
        
    }//GEN-LAST:event_clock_inMouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        
        empID_ti();
        // Time out
        
        PreparedStatement st;
        ResultSet rst;

        //get employee ID
        
        int stump = Integer.parseInt(stamp_no.getText());
        String stomp = Integer.toString(stump - 1); 
        
        
        String date_today = date_time.getText();
        String user = empID_t.getText();
        
        //create a select query to pull data from employee database
        String query = "SELECT * FROM motorphemployeedb.`attendance_record_test` WHERE `Date` = ? AND `Employee_no` = ? AND `Stamp` = ?  ";
        //create a select query to pull data from attendance database

        
        try{
            st = (PreparedStatement) db.getConnection().prepareStatement(query);
            st.setString(1,date_today);
            st.setString(2,user);
            st.setString(3,stomp);
            
            
            
            
            rst = st.executeQuery();
           

            if(rst.next()){
                
                
                
                String query2 = "SELECT * FROM motorphemployeedb.`attendance_record_test` WHERE `Time_out` IS NULL";
                
                st = (PreparedStatement) db.getConnection().prepareStatement(query2);
//                st.setString(1,stomp);
                
                
                rst = st.executeQuery();
                
                    if (rst.next()){ 
                        
                        
//                        JOptionPane.showMessageDialog(this,"You already logged out.");

                    String timetoday = time_time.getText();

//                    String empID = empID_t.getText();

 
                      String sql = "Update motorphemployeedb.`attendance_record_test` set Time_out = ? WHERE Stamp = ?";  


                    try (PreparedStatement statement = db.getConnection().prepareStatement(sql)){  

                        statement.setString(1,timetoday);
                        statement.setString(2,stomp);
                        statement.executeUpdate();

                    }

                    JOptionPane.showMessageDialog(this,"<html><br>You have now logged out.<br>Thank you for your hard word!<br></html>");

                    load_table1();
                    in_out_time();
                    id_increment_time();

                }else{
                        JOptionPane.showMessageDialog(this,"You already logged out.");
                        
                    
                    }
                    
                

                
                }else{
                

                
                JOptionPane.showMessageDialog(this,"You are yet to clocked-in today.");
                
               
                
            }
            
        } catch (HeadlessException | SQLException e) {
            Logger.getLogger(maindash.class.getName()).log(Level.SEVERE, null, e);
        }
    
    }//GEN-LAST:event_jPanel7MouseClicked

    
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(255,255,255));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(204,204,204));
    }
    
    
    
  
    public void datetime() {
    
        Date d = new Date();
        
        SimpleDateFormat dnt = new SimpleDateFormat("MM/dd/yyyy");
        
        String dd = dnt.format(d);
        
        date_time.setText(dd);
    
    
    }
    
    
        Timer t;
        SimpleDateFormat bd;
    
    public void timetime(){
        
        
        
        
        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
            
            Date dt = new Date();
            bd =new SimpleDateFormat("HH:mm");
            
            
            String tt =bd.format(dt);
            time_time.setText(tt);
                
            }
        });
        
        t.start();
        
        
        
        
    }
    
    
   
    
    public void in_out_time(){
        
        PreparedStatement st;
        ResultSet rs;

        
        
        String user = empID_t.getText();
        String date_today = date_time.getText();
        //get employee ID
        
        
        //create a select query to pull data from employee database
        String query = "SELECT * FROM motorphemployeedb.`attendance_record_test`WHERE `Employee_no` = ? AND `Date` =?";
        String[] columnNames = {"Time_in","Time_out"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames,0);
        //create a select query to pull data from attendance database 

        
        try{
            st = (PreparedStatement) db.getConnection().prepareStatement(query);
            st.setString(1,user);
            st.setString(2,date_today);
            
            rs = st.executeQuery();
           

            while(rs.next()){
            
              String  Time_in= rs.getString("Time_in");
              String  Time_out= rs.getString("Time_out");
              
              
              // create a single array of one row's worth of data
                String[] data = { Time_in, Time_out } ;

              // and add this row of data into the table model
              tableModel.addRow(data);
                


            }
            jTable2.setModel(tableModel); // place model into JTable
            
            
        } catch (SQLException ex) {
            Logger.getLogger(maindash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    public void id_increment_time(){
        // to add stamp on database
        
        PreparedStatement st;
        ResultSet rs;
       
        
        //create a select query to pull data from employee database
        String query = "SELECT `Stamp` FROM motorphemployeedb.`attendance_record_test` ORDER BY `Stamp` DESC LIMIT 1";
        
        try {
            
            st = (PreparedStatement) db.getConnection().prepareStatement(query);
           
            rs = st.executeQuery();
            
            if (rs.next()){
                
                int stamp =rs.getInt(1);
                int n = stamp+1;
                
                stamp_no.setText(Integer.toString(n)); 
                
            }
            
            
        }catch(Exception e){
            JOptionPane.showInputDialog(null,e);
        }
        
        
    }
    
    
    public void load_table1(){
        
        PreparedStatement st;
        ResultSet rs;

        
        int sum = Integer.parseInt(empid_time.getText())+10000;
        String user = Integer.toString(sum);
        //get employee ID
        
        
        //create a select query to pull data from employee database
        String query = "SELECT * FROM motorphemployeedb.`attendance_record_test`WHERE `Employee_no` = ? ORDER BY `Stamp` DESC";
        String[] columnNames = {"Date","Time_in","Time_out"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames,0);
        //create a select query to pull data from attendance database 

        
        try{
            st = (PreparedStatement) db.getConnection().prepareStatement(query);
            st.setString(1,user);
            
            rs = st.executeQuery();
           

            while(rs.next()){
            
              String Date = rs.getString("Date");
              String  Time_in= rs.getString("Time_in");
              String  Time_out= rs.getString("Time_out");
              
              
              // create a single array of one row's worth of data
                String[] data = { Date, Time_in, Time_out } ;

              // and add this row of data into the table model
              tableModel.addRow(data);
                
              empID_t.setText(user);
              id_increment_time();
                


            }
            jTable1.setModel(tableModel); // place model into JTable
            
            
        } catch (SQLException ex) {
            Logger.getLogger(maindash.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    public void empID_ti(){
        
        int sum = Integer.parseInt(empid_time.getText())+10000;
        String user = Integer.toString(sum);
        
        empID_t.setText(user);
        
        
    }
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        
        
        
        
        
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new maindash().setVisible(true);
//            }
//        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Comp_post;
    private javax.swing.JLabel Department;
    private javax.swing.JLabel EmpID;
    private javax.swing.JLabel EmpID_num;
    private javax.swing.JPanel EmpInfoPanel;
    private javax.swing.JLabel EmpName;
    private javax.swing.JPanel MainDash;
    private javax.swing.JPanel PayslipPanel;
    private javax.swing.JPanel Time_AttendPanel;
    private javax.swing.JLabel acctno_info;
    private javax.swing.JLabel add_info;
    private javax.swing.JLabel bday_info;
    private javax.swing.JPanel btn_EmpInfo;
    private javax.swing.JPanel btn_Payslip;
    private javax.swing.JPanel btn_Time_Attend;
    private javax.swing.JPanel clock_in;
    private javax.swing.JLabel cloth_sum;
    private javax.swing.JLabel compost_info;
    private javax.swing.JLabel date_time;
    private javax.swing.JLabel empID_t;
    private javax.swing.JLabel empid_payslip;
    private javax.swing.JLabel empid_time;
    private javax.swing.JLabel empstatus_info;
    private javax.swing.JLabel hdmf_info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel name_time;
    private javax.swing.JLabel netPay;
    private javax.swing.JLabel payoutdate;
    private javax.swing.JLabel payoutdate1;
    private javax.swing.JLabel payoutdate4;
    private javax.swing.JLabel payoutdate7;
    private javax.swing.JLabel payperiod;
    private javax.swing.JLabel phil_info;
    private javax.swing.JLabel phone_info;
    private javax.swing.JLabel phone_sum;
    private javax.swing.JLabel rice_sum;
    private javax.swing.JLabel sss_info;
    private javax.swing.JLabel stamp_no;
    private javax.swing.JLabel sup_info;
    private javax.swing.JLabel t_f_name;
    private javax.swing.JLabel t_l_name;
    private javax.swing.JLabel time_time;
    private javax.swing.JLabel tin_info;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel total_ben;
    private javax.swing.JLabel ttlDeductions;
    private javax.swing.JLabel ttlEarning;
    // End of variables declaration//GEN-END:variables



}
